services:
  auth:
    build:
      context: ./authentification
    container_name: auth
    networks:
      - my_network
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY=ma_clé_secrète
      - DN_FRONT=front

  front:
    build:
      context: ./front
    container_name: front
    networks:
      - my_network
    ports:
      - "3001:3001"
    environment:
      - SECRET_KEY_SESSION=ma_clé_session
      - SECRET_KEY_AUTH=ma_clé_secrète
      - DN_AUTH=auth
      - DN_PDF=pdf
      - DN_CLIENT=client

  client:
    networks:
      - my_network
    build:
      context: ./client
    container_name: client
    ports:
      - "8080:8080"
    environment:
      - DN_FRONT=front

  pdf:
    build:
      context: ./pdf
    container_name: pdf
    networks:
      - my_network
    ports:
      - "3002:3002"

networks:
  my_network:
    driver: bridge
